import { AiFillHtml5 } from "react-icons/ai";
import {
  FaAndroid,
  FaCode,
  FaNodeJs,
  FaReact,
  FaUnity,
  FaHotel,
  FaAws,
  FaCss3Alt,
  FaDocker,
  FaGitAlt,
  FaHtml5,
  FaJava,
  FaPython,
  FaCloud,
  FaLayerGroup,
  FaDatabase,
  FaGlobe,
  FaLaptopCode,
  FaUsers,
} from "react-icons/fa6";
import {
  RiComputerLine,
  RiDatabase2Line,
  RiSimCard2Line,
} from "react-icons/ri";
import {
  SiCplusplus,
  SiDjango,
  SiEclipseide,
  SiFigma,
  SiFirebase,
  SiJavascript,
  SiKotlin,
  SiMongodb,
  SiNextdotjs,
  SiPostgresql,
  SiRubyonrails,
  SiTailwindcss,
  SiTensorflow,
} from "react-icons/si";
import {
  IAcademics,
  IAchievement,
  IExperience,
  IProject,
  ISkill,
  ISkillGroup,
} from "./data-type";

export const experiences: Array<IExperience> = [
  {
    id: 1,
    title: "experience.meroparty.title",
    role: "experience.meroparty.role",
    location: "experience.meroparty.location",
    date: "experience.meroparty.date",
    description: "experience.meroparty.description",
    image: "https://meroparty.com/assets/mero-party-logo-y-470e799b.avif",
    category: "Development",
    Icon: FaHotel,
  },
  {
    id: 2,
    title: "experience.icc.title",
    role: "experience.icc.role",
    location: "experience.icc.location",
    date: "experience.icc.date",
    description: "experience.icc.description",
    image: "https://picsum.photos/200/300", // Replace with ICC logo if available
    category: "Sales & Support",
    Icon: RiSimCard2Line,
  },
  {
    id: 3,
    title: "experience.axiosSoftworks.title",
    role: "experience.axiosSoftworks.role",
    location: "experience.axiosSoftworks.location",
    date: "experience.axiosSoftworks.date",
    description: "experience.axiosSoftworks.description",
    image: "https://picsum.photos/200/301",
    category: "Development",
    Icon: RiComputerLine,
  },
  {
    id: 4,
    title: "experience.cloudFactory.title",
    role: "experience.cloudFactory.role",
    location: "experience.cloudFactory.location",
    date: "experience.cloudFactory.date",
    description: "experience.cloudFactory.description",
    image: "https://picsum.photos/200/302",
    category: "Data Science",
    Icon: RiDatabase2Line,
  },
];

export const languages: Array<ISkill> = [
  {
    id: 1,
    title: "HTML & CSS",
    Icon: AiFillHtml5,
    level: "90%",
    category: "Front-End",
  },
  {
    id: 3,
    title: "JavaScript",
    Icon: SiJavascript,
    level: "70%",
    category: "Front-End",
  },
  {
    id: 4,
    title: "React",
    Icon: FaReact,
    level: "60%",
    category: "Front-End",
  },
  {
    id: 5,
    title: "Node",
    Icon: FaNodeJs,
    level: "70%",
    category: "Back-End",
  },
  {
    id: 6,
    title: "Ruby on Rails",
    Icon: SiRubyonrails,
    level: "40%",
    category: "Back-End",
  },
  {
    id: 7,
    title: "Kotlin",
    Icon: SiKotlin,
    level: "75%",
    category: "App-End",
  },
];

export const tools: Array<ISkill> = [
  {
    id: 1,
    title: "VS Code",
    Icon: FaCode,
    level: "90%",
    category: "Full-Stack",
  },
  {
    id: 2,
    title: "Android Studio",
    Icon: FaAndroid,
    level: "80%",
    category: "Full-Stack",
  },
  {
    id: 3,
    title: "Unity",
    Icon: FaUnity,
    level: "70%",
    category: "Full-Stack",
  },
  {
    id: 4,
    title: "Eclipse",
    Icon: SiEclipseide,
    level: "60%",
    category: "Full-Stack",
  },
];

export const academics: Array<IAcademics> = [
  {
    id: 1,
    organization: "academics.sijli.title",
    image: "https://picsum.photos/200/300",
    degree: "academics.sijli.degree",
    year: "academics.sijli.year",
    address: "academics.sijli.address",
  },
  {
    id: 2,
    organization: "academics.glocal.title",
    image: "https://picsum.photos/200/300",
    degree: "academics.glocal.degree",
    year: "academics.glocal.year",
    address: "academics.glocal.address",
  },
  {
    id: 3,
    organization: "academics.kantipur.title",
    image: "https://picsum.photos/200/300",
    degree: "academics.kantipur.degree",
    year: "academics.kantipur.year",
    address: "academics.kantipur.address",
  },
  {
    id: 4,
    organization: "academics.kanjirowa.title",
    image: "https://picsum.photos/200/300",
    degree: "academics.kanjirowa.degree",
    year: "academics.kanjirowa.year",
    address: "academics.kanjirowa.address",
  },
  {
    id: 5,
    organization: "academics.himalayan.title",
    image: "https://picsum.photos/200/300",
    degree: "academics.himalayan.degree",
    year: "academics.himalayan.year",
    address: "academics.himalayan.address",
  },
];

export const projects: Array<IProject> = [
  {
    id: 1,
    name: "projects.zBlog.title",
    description: "projects.zBlog.description",
    image: "https://picsum.photos/200/300",
    category: ["node", "mongodb", "all"],
    url_deployed: "https://warm-journey-16132.herokuapp.com/",
    url_github: "https://www.google.com",
    key_features: [
      "Node JS",
      "Node",
      "MongoDB",
      "Bootstrap",
      "Jquery",
      "fontAwesome",
    ],
  },
  {
    id: 2,
    name: "projects.zeitsuETrade.title",
    description: "projects.zeitsuETrade.description",
    image: "https://picsum.photos/200/300",
    category: ["laravel", "php", "all"],
    url_deployed: "https://zeitsuetrade.000webhostapp.com",
    url_github: "https://www.google.com",
    key_features: [
      "PHP",
      "MySQL Database",
      "Bootstrap",
      "Jquery",
      "fontAwesome",
    ],
  },
  {
    id: 3,
    name: "projects.gbcc.title",
    description: "projects.gbcc.description",
    image: "/assets/images/projects/gbmc.png",
    category: ["python"],
    url_deployed: "https://www.google.com",
    url_github: "https://www.google.com",
    key_features: ["Anaconda", "Python", "Numpy", "pyautogui", "OpenCV"],
  },
  {
    id: 4,
    name: "projects.vKec.title",
    description: "projects.vKec.description",
    image: "https://picsum.photos/200/300",
    category: ["javascript", "c#"],
    url_deployed: "https://www.google.com",
    url_github: "https://www.google.com",
    key_features: [
      "Unity",
      "Autodesk 3DS Max",
      "Blender for Modeling",
      "Adobe Photoshop-textures",
    ],
  },
  {
    id: 5,
    name: "projects.runner.title",
    description: "projects.runner.description",
    image: "https://picsum.photos/200/300",
    category: ["c++"],
    url_deployed: "https://www.google.com",
    url_github: "https://www.google.com",
    key_features: ["CodeBlocks", "C++", "graphics.h"],
  },
  {
    id: 6,
    name: "projects.companyDB.title",
    description: "projects.companyDB.description",
    image: "https://picsum.photos/200/300",
    category: ["c++"],
    url_deployed: "https://www.google.com",
    url_github: "https://www.google.com",
    key_features: ["Dev C++", "C++"],
  },
  {
    id: 7,
    name: "projects.plustwonotes.title",
    description: "projects.plustwonotes.description",
    image: "/assets/images/projects/plus2notes.png",
    category: ["laravel", "vue", "all"],
    url_deployed: "https://www.google.com",
    url_github: "https://www.google.com",
    key_features: ["Laravel", "PHP", "stripe"],
  },
  {
    id: 8,
    name: "projects.meroparty.title",
    description: "projects.meroparty.description",
    image: "/assets/images/projects/meroparty.png",
    category: ["typescript", "react", "javascript", "all"],
    url_deployed: "https://www.meroparty.com",
    url_github: "https://www.meroparty.com",
    key_features: ["React", "TypeScript", "Vite", "React", "FramerMotion"],
  },
];

export const skillGroups: ISkillGroup[] = [
  {
    category: "skillGroups.programming",
    Icon: FaCode,
    skills: [
      {
        id: 1,
        title: "C",
        category: "Programming",
        Icon: SiCplusplus,
        level: "80%",
      },
      {
        id: 2,
        title: "C++",
        category: "Programming",
        Icon: SiCplusplus,
        level: "75%",
      },
      {
        id: 3,
        title: "Java",
        category: "Programming",
        Icon: FaJava,
        level: "85%",
      },
      {
        id: 4,
        title: "JavaScript",
        category: "Programming",
        Icon: SiJavascript,
        level: "90%",
      },
      {
        id: 5,
        title: "Python",
        category: "Programming",
        Icon: FaPython,
        level: "80%",
      },
      {
        id: 6,
        title: "SQL",
        category: "Programming",
        Icon: SiPostgresql,
        level: "85%",
      },
    ],
  },
  {
    category: "skillGroups.fullStack",
    Icon: FaLayerGroup,
    skills: [
      {
        id: 7,
        title: "HTML5",
        category: "Full-Stack",
        Icon: FaHtml5,
        level: "95%",
      },
      {
        id: 8,
        title: "CSS3",
        category: "Full-Stack",
        Icon: FaCss3Alt,
        level: "90%",
      },
      {
        id: 9,
        title: "React",
        category: "Full-Stack",
        Icon: FaReact,
        level: "88%",
      },
      {
        id: 10,
        title: "Next.js",
        category: "Full-Stack",
        Icon: SiNextdotjs,
        level: "85%",
      },
      {
        id: 11,
        title: "Tailwind",
        category: "Full-Stack",
        Icon: SiTailwindcss,
        level: "90%",
      },
      {
        id: 12,
        title: "Node.js",
        category: "Full-Stack",
        Icon: FaNodeJs,
        level: "82%",
      },
      {
        id: 13,
        title: "Django",
        category: "Full-Stack",
        Icon: SiDjango,
        level: "70%",
      },
    ],
  },
  {
    category: "skillGroups.devOps",
    Icon: FaCloud,
    skills: [
      { id: 14, title: "AWS", category: "Cloud", Icon: FaAws, level: "65%" },
      {
        id: 15,
        title: "Firebase",
        category: "Cloud",
        Icon: SiFirebase,
        level: "80%",
      },
      {
        id: 16,
        title: "Docker",
        category: "Cloud",
        Icon: FaDocker,
        level: "75%",
      },
      {
        id: 17,
        title: "CI/CD Pipelines",
        category: "Cloud",
        Icon: FaGitAlt,
        level: "70%",
      },
    ],
  },
  {
    category: "skillGroups.database",
    Icon: FaDatabase,
    skills: [
      {
        id: 18,
        title: "MySQL",
        category: "Databases",
        Icon: SiPostgresql,
        level: "85%",
      },
      {
        id: 19,
        title: "PostgreSQL",
        category: "Databases",
        Icon: SiPostgresql,
        level: "80%",
      },
      {
        id: 20,
        title: "MongoDB",
        category: "Databases",
        Icon: SiMongodb,
        level: "78%",
      },
    ],
  },
  {
    category: "skillGroups.uiux",
    Icon: FaDatabase,
    skills: [
      {
        id: 21,
        title: "Figma",
        category: "Design",
        Icon: SiFigma,
        level: "85%",
      },
      {
        id: 22,
        title: "Adobe Photoshop",
        category: "Design",
        Icon: SiFigma,
        level: "70%",
      },
      {
        id: 23,
        title: "Adobe Illustrator",
        category: "Design",
        Icon: SiFigma,
        level: "70%",
      },
      {
        id: 24,
        title: "Canva",
        category: "Design",
        Icon: SiFigma,
        level: "70%",
      },
    ],
  },
  {
    category: "skillGroups.machineLearning",
    Icon: FaDatabase,
    skills: [
      {
        id: 25,
        title: "TensorFlow",
        category: "Machine Learning",
        Icon: SiTensorflow,
        level: "60%",
      },
      {
        id: 26,
        title: "Pandas",
        category: "Machine Learning",
        Icon: FaPython,
        level: "75%",
      },
    ],
  },
];

export const trainingsAndParticipations: Array<IExperience> = [
  {
    id: 1,
    title: "trainingsAndParticipations.bigData.title",
    role: "trainingsAndParticipations.bigData.role",
    location: "trainingsAndParticipations.bigData.location",
    date: "trainingsAndParticipations.bigData.date",
    description: "trainingsAndParticipations.bigData.description",
    category: "Participation",
    Icon: FaDatabase,
    image: "",
  },
  {
    id: 2,
    title: "trainingsAndParticipations.studentICT.title",
    role: "trainingsAndParticipations.studentICT.role",
    location: "trainingsAndParticipations.studentICT.location",
    date: "trainingsAndParticipations.studentICT.date",
    description: "trainingsAndParticipations.studentICT.description",
    category: "Participation",
    Icon: FaUsers,
    image: "",
  },
  {
    id: 3,
    title: "trainingsAndParticipations.yCC.title",
    role: "trainingsAndParticipations.yCC.role",
    location: "trainingsAndParticipations.yCC.location",
    date: "trainingsAndParticipations.yCC.date",
    description: "trainingsAndParticipations.yCC.description",
    category: "Participation",
    Icon: FaUnity,
    image: "",
  },
  {
    id: 4,
    title: "trainingsAndParticipations.advJava.title",
    role: "trainingsAndParticipations.advJava.role",
    location: "trainingsAndParticipations.advJava.location",
    date: "trainingsAndParticipations.advJava.date",
    description: "trainingsAndParticipations.advJava.description",
    category: "Training",
    Icon: FaCode,
    image: "",
  },
  {
    id: 5,
    title: "trainingsAndParticipations.androidDev.title",
    role: "trainingsAndParticipations.androidDev.role",
    location: "trainingsAndParticipations.androidDev.location",
    date: "trainingsAndParticipations.androidDev.date",
    description: "trainingsAndParticipations.androidDev.description",
    category: "Training",
    Icon: FaAndroid,
    image: "",
  },
  {
    id: 6,
    title: "trainingsAndParticipations.webDevCamp.title",
    role: "trainingsAndParticipations.webDevCamp.role",
    location: "trainingsAndParticipations.webDevCamp.location",
    date: "trainingsAndParticipations.webDevCamp.date",
    description: "trainingsAndParticipations.webDevCamp.description",
    category: "Participation",
    Icon: FaGlobe,
    image: "",
  },
  {
    id: 7,
    title: "trainingsAndParticipations.krustile.title",
    role: "trainingsAndParticipations.krustile.role",
    location: "trainingsAndParticipations.krustile.location",
    date: "trainingsAndParticipations.krustile.date",
    description: "trainingsAndParticipations.krustile.description",
    category: "Training",
    Icon: FaLaptopCode,
    image: "",
  },
];

export const achievements: Array<IAchievement> = [
  {
    id: 1,
    type: "Certification",
    date: "achievements.jlpt.date",
    title: "achievements.jlpt.title",
    achievement: "achievements.jlpt.achievement",
    description: "achievements.jlpt.description",
  },
  {
    id: 2,
    type: "Award",
    date: "achievements.yCC.date",
    title: "achievements.yCC.title",
    achievement: "achievements.yCC.achievement",
    description: "achievements.yCC.description",
    location: "achievements.yCC.description",
  },
  {
    id: 3,
    type: "Award",
    date: "achievements.digitalAd.date",
    title: "achievements.digitalAd.title",
    achievement: "achievements.digitalAd.achievement",
    description: "achievements.digitalAd.description",
    location: "achievements.digitalAd.description",
  },
];
